### ISSUE TITLE
Warn the user not to keep the config file under version control

### ISSUE THREAD

**Issue by benjie** [dijam/graphile-jwt-example#4]
Because it includes secrets such as database username/password, JWT secret, etc.; keeping these under version control is not best practices.

Alternatively allow the user to override these via environmental variables or some other means.

**Comment by dijam** [comment]
So, `good-config` has this functionality in its core. You can replace any config key via env variables but envifying the name. For example: 
```
server:
  port: 3000
```

can we overwritten by env variable of `SERVER_PORT=3001`

**Comment by benjie** [comment]
Perfect; do make sure to mention this in the README 👍

**Comment by dijam** [comment]
Done in #7
